P8105 - HW2
================
Due: 2024-10-02

Author: Ravi Brenner (irb2118)

# Introduction

This Rmarkdown document is for P8105 - Data Science 1, homework 2.

# Methods

The data for this homework comes from the course website, but all files
can be found in the `data/` folder. Additionally, we will be using
packages from the `tidyverse`

``` r
library(tidyverse)
```

# Problems

## Problem 1

This problem is about the NYC subway system.

First, we must read in the data, clean up the column names, and select
and transform the columns that we need:

``` r
subway_df <-
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entry,
    vending,
    entrance_type,
    ada
  ) |>
  mutate(entry = case_match(entry,
                            "YES" ~ TRUE,
                            "NO" ~ FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

This dataset contains data on each entrance and exit for each subway
line and station (name and geographic location), and the routes that
operate at the line and station (for example, some stops accomodate
multiple trains on the same line, like the NQRW or the 123). There are
additional variables indicating the entrance type, presence of vending
machines, and ADA compliance.

So far, I imported the data using `read_csv`, cleaned up the column
names using `janitor::clean_names`, selected the relevant columns using
`select`, and transformed the `entry` column from character to logical.
After these steps, there are 1868 rows and 19 columns.

#### How many distinct stations are there?

``` r
subway_df |>
  distinct(line,station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

#### How many stations are ADA compliant?

``` r
subway_df |>
  filter(ada == TRUE) |>
  distinct(line,station_name) |>
  nrow()
```

    ## [1] 84

84 stations are ADA compliant.

#### What proportion of station entrances / exits without vending allow entrance?

``` r
subway_df |>
  filter(vending == "NO") |>
  janitor::tabyl(entry)
```

    ##  entry   n   percent
    ##  FALSE 114 0.6229508
    ##   TRUE  69 0.3770492

37.7% of station entrances without vending allow entrance.

Now, I will reformat the data from wide to long, into proper tidy
format:

``` r
subway_df <- subway_df |>
  mutate(across(.cols = route8:route11,
                as.character)) |>
  pivot_longer(cols = route1:route11,
               names_to = "route_number",
               values_to = "route_name",
               names_prefix = "route") |>
  drop_na(route_name)
```

#### How many distinct stations serve the A train?

``` r
subway_df |>
  filter(route_name == "A") |>
  distinct(line,station_name) |>
  nrow()
```

    ## [1] 60

60 distinct stations serve the A train.

#### Of the stations that serve the A train, how many are ADA compliant?

``` r
subway_df |>
  filter(route_name == "A") |>
  distinct(line,station_name,ada) |>
  janitor::tabyl(ada)
```

    ##    ada  n   percent
    ##  FALSE 43 0.7166667
    ##   TRUE 17 0.2833333

17/60 stations that serve the A train, or 28.3%, are ADA compliant.

## Problem 2

## Problem 3

# Conclusion
